version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 20

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/Oslo"
    cooldown:
      default-days: 7
    open-pull-requests-limit: 10
