apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ufore-varsler
  namespace: ufore
  labels:
    team: ufore
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-g1-small
        databases:
          - name: ufore-varsler
            envVarPrefix: DB
            users:
              - name: ufore-varsler-send-jobb
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "9e122ddd-e542-4cc1-a7eb-92c99140fe0e" # 0000-GA-PENSJON_BRUKERHJELPA
          - id: "05ae245b-7b47-428a-9074-4ff6b59eddbc" # 0000-GA-Pensjon_Okonomi
          - id: "8bb9b8d1-f46a-4ade-8ee8-5895eccdf8cf" # 0000-GA-PENSJON_SAKSBEHANDLER
          - id: "a3f91493-1ab8-4b64-a544-0a77cbba9240" # 0000-GA-Pensjon_VEILEDER
          - id: "dbe4ad45-320b-4e9a-aaa1-73cca4ee124d" # 0000-GA-Egne_ansatte
          - id: "2e1dc582-f762-4510-a660-88bf68fb7128" # 0000-GA-Fortrolig_Adresse
          - id: "a1b518e2-3947-478d-8929-e5d685c47cac" # 0000-GA-Strengt_Fortrolig_Adresse
  accessPolicy:
    inbound:
      rules:
        - application: din-uforetrygd-frontend-borger
          cluster: dev-gcp
        - application: din-uforetrygd-frontend-veileder
          cluster: dev-gcp
    outbound:
      rules:
        - application: pensjon-pid-encryption
          namespace: pensjon-person
      external:
        - host: ufore-unleash-api.nav.cloud.nais.io
  envFrom:
    - secret: ufore-varsler-unleash-api-token
  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: KAFKA_SECURITY_PROTOCOL
      value: SSL
