apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ufore-varsler
  namespace: ufore
  labels:
    team: ufore
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-prod
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  accessPolicy:
    outbound:
      external: []
  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: KAFKA_SECURITY_PROTOCOL
      value: SSL
