apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: ufore-varsler
  namespace: ufore
  labels:
    team: ufore
spec:
  image: "{{ image }}"
  port: 8080
  liveness:
    path: actuator/health/liveness
    initialDelay: 30
  readiness:
    path: actuator/health/readiness
    initialDelay: 30
  startup:
    path: actuator/health/readiness
    initialDelay: 30
    failureThreshold: 30
    periodSeconds: 5
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: elastic
        - id: loki
  kafka:
    pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-g1-small
        databases:
          - name: ufore-varsler
            envVarPrefix: DB
            users:
              - name: ufore-varsler-send-jobb
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  prometheus:
    enabled: true
    path: actuator/prometheus
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e" #SAKSBEHANDLER
          - id: "7845a796-1516-4d14-b500-fd65c001f35c" #BRUKERHJELPA
          - id: "959ead5b-99b5-466b-a0ff-5fdbc687517b" #VEILEDER
          - id: "70ef8e7f-7456-4298-95e0-b13c0ef2422b" #OKONOMI
          - id: "2931da41-8b8e-42cd-99c0-04a169ddae40" #STRENGT_FORTROLIG
          - id: "e98efc34-12d1-401f-b059-f17e62834065" #FORTROLIG
          - id: "e750ceb5-b70b-4d94-b4fa-9d22467b786b" #EGENANSATT
  accessPolicy:
    inbound:
      rules:
        - application: din-uforetrygd-frontend-borger
          cluster: prod-gcp
        - application: din-uforetrygd-frontend-veileder
          cluster: prod-gcp
    outbound:
      rules:
        - application: pensjon-pid-encryption
          namespace: pensjon-person
        - application: skjermede-personer-pip
          namespace: nom
      external:
        - host: ufore-unleash-api.nav.cloud.nais.io
        - host: pensjon-representasjon.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
  envFrom:
    - secret: ufore-varsler-unleash-api-token
  env:
    - name: LOGGING_CONFIG
      value: classpath:logback-json.xml
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: KAFKA_SECURITY_PROTOCOL
      value: SSL
