spring:
  main:
    web-application-type: none
  kafka:
    listener:
      auto-startup: false
  flyway:
    enabled: false
  datasource:
    url: ${DB_UFORE_VARSLER_SEND_JOBB_JDBC_URL}

app:
  texas:
    token-introspection-endpoint: http://localhost:0/not-in-use