spring:
  main:
    web-application-type: none
  kafka:
    listener:
      auto-startup: false
  flyway:
    enabled: false
  datasource:
    url: ${DB_UFORE_VARSLER_SEND_JOBB_JDBC_URL}
    username: ${DB_UFORE_VARSLER_SEND_JOBB_USERNAME}
    password: ${DB_UFORE_VARSLER_SEND_JOBB_PASSWORD}
    hikari:
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ufore-dev-dfc9:europe-north1:ufore-varsler

app:
  texas:
    token-introspection-endpoint: http://localhost:0/not-in-use