spring:
  application:
    name: ufore-varsler-send-jobb
  main:
    web-application-type: none
  kafka:
    listener:
      auto-startup: false
  flyway:
    enabled: false
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://${DB_UFORE_VARSLER_SEND_JOBB_HOST}:${DB_UFORE_VARSLER_SEND_JOBB_PORT}/${DB_UFORE_VARSLER_SEND_JOBB_DATABASE}
      username: ${DB_UFORE_VARSLER_SEND_JOBB_USERNAME}
      password: ${DB_UFORE_VARSLER_SEND_JOBB_PASSWORD}
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${CLOUDSQL_INSTANCE}

app:
  token:
    introspection-endpoint: http://localhost:0/not-in-use
    exchange-endpoint: http://localhost:0/not-in-use
    m2m-endpoint: http://localhost:0/not-in-use
