spring:
  application:
    name: ufore-varsler
  profiles:
    default: local
  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  datasource:
    hikari:
      jdbc-url: ${DB_JDBC_URL}
      driver-class-name: org.postgresql.Driver
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS:localhost:9092}
    client-id: ${spring.application.name}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      ssl.truststore.location: ${KAFKA_TRUSTSTORE_PATH:}
      ssl.truststore.password: ${KAFKA_CREDSTORE_PASSWORD:}
      ssl.keystore.location: ${KAFKA_KEYSTORE_PATH:}
      ssl.keystore.password: ${KAFKA_CREDSTORE_PASSWORD:}
      ssl.key.password: ${KAFKA_CREDSTORE_PASSWORD:}

app:
  unleash:
    url: ${UNLEASH_SERVER_API_URL}/api
    token: ${UNLEASH_SERVER_API_TOKEN}
  texas:
    token-introspection-endpoint: ${NAIS_TOKEN_INTROSPECTION_ENDPOINT}
    token-exchange-endpoint: ${NAIS_TOKEN_EXCHANGE_ENDPOINT}
  kafka:
    min-side:
      varsel-hendelse: min-side.aapen-varsel-hendelse-v1
      consumer-group-id: ufore-varsler-varsel-hendelse-consumer
      brukervarsel: min-side.aapen-brukervarsel-v1
    ufore-varsler:
      topic: ufore.varsler
      consumer-group-id: ufore-varsler-consumer
  dine-muligheter-url: https://nav.no/uforetrygd/selvbetjening/dine-muligheter
  pushgateway:
    address: ${PUSH_GATEWAY_ADDRESS:prometheus-pushgateway.nais-system:9091}
  pid-encryption:
    url: http://pensjon-pid-encryption.pensjon-person
    target: prod-gcp.pensjon-person.pensjon-pid-encryption

ad-grupper:
  skjermet: e750ceb5-b70b-4d94-b4fa-9d22467b786b
  fortrolig: e98efc34-12d1-401f-b059-f17e62834065
  strengt-fortrolig: 2931da41-8b8e-42cd-99c0-04a169ddae40
  brukerhjelpa: 7845a796-1516-4d14-b500-fd65c001f35c
  okonomi: 70ef8e7f-7456-4298-95e0-b13c0ef2422b
  saksbehandler: 0af3955f-df85-4eb0-b5b2-45bf2c8aeb9e
  veileder: 959ead5b-99b5-466b-a0ff-5fdbc687517b

management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: prometheus, health, info, gateway
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99