app:
  dine-muligheter-url: https://uforetrygd-selvbetjening-frontend-borger.intern.dev.nav.no/uforetrygd/selvbetjening/dine-muligheter
  pid-encryption:
    target: dev-gcp.pensjon-person.pensjon-pid-encryption