name: Apply alerts

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/apply-alerts.yml'
      - 'alerts/**'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      - uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alerts.yaml
