name: Apply alerts

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/apply-alerts.yml'
      - 'alerts/**'

jobs:
  apply-alerts:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: prod-gcp
          RESOURCE: alerts/alerts.yaml
