name: "Dev: ufore-varsler deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: dev-ufore-varsler-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Bygg og publiser Docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Setup java
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bygg
        run: ./gradlew build

      - name: docker-build-push
        uses: nais/docker-build-push@751a312f0803eb96a05a41fadf51be19b7be362c
        id: docker-build-push
        with:
          team: ufore
          dockerfile: Dockerfile

  deploy-to-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          TEAM: ufore
