name: "Dev: ufore-varsler deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: dev-ufore-varsler-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Bygg og publiser Docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Setup java
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle cache
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bygg
        run: ./gradlew build

      - name: docker-build-push
        uses: nais/docker-build-push@05dbb6091b30bd84279c6d64a45ef8782fd410a5
        id: docker-build-push
        with:
          team: ufore
          dockerfile: Dockerfile

  deploy-to-dev:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Deploy til dev
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/dev.yaml, .nais/topic-dev.yaml, .nais/unleash-apitoken-dev.yaml
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          TEAM: ufore

      - name: Deploy påminnelsesjobb til dev
        uses: nais/deploy/actions/deploy@5fdd91aaf69bb0d6dd5e5118cdacb639f487b93b
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/job-dev.yaml,.nais/network-policy-dev.yaml
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          TEAM: ufore
