name: "Prod: ufore-varsler deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: prod-ufore-varsler-deploy
  cancel-in-progress: true

jobs:
  build-and-push:
    name: Bygg og publiser Docker-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Setup java
        uses: actions/setup-java@c1e323688fd81a25caa38c78aa6df2d33d3e20d9
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle cache
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Bygg
        run: ./gradlew build

      - name: docker-build-push
        uses: nais/docker-build-push@be85229e81c0293c265c646c084f05317fb6e0d2
        id: docker-build-push
        with:
          team: ufore
          dockerfile: Dockerfile

  trivy-docker:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write
      security-events: write

    steps:
      - uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f
        with:
          team: ufore

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # 0.35.0
        with:
          image-ref: ${{ needs.build-and-push.outputs.image }}
          format: 'sarif'
          output: 'trivy.sarif'
          severity: 'HIGH,CRITICAL'
          limit-severities-for-sarif: true

      - name: Upload results to GitHub Security
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225
        with:
          sarif_file: 'trivy.sarif'

  deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Deploy til prod
        uses: nais/deploy/actions/deploy@2f28259ff29ea37915f5a0c9e2a8e3542c429df7
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/prod.yaml, .nais/topic-prod.yaml, .nais/unleash-apitoken-prod.yaml
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          TEAM: ufore

      - name: Deploy påminnelsesjobb til prod
        uses: nais/deploy/actions/deploy@849e900e3cfa7faf7ad1532bb3a3e6499c932199
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/job-prod.yaml,.nais/network-policy-prod.yaml
          IMAGE: ${{ needs.build-and-push.outputs.image }}
          TEAM: ufore
